### ISSUE TITLE
Track not handling failure from server properly

### ISSUE THREAD

**Issue by troykelly** [troykelly/python-nswcovid#12]
Per https://github.com/troykelly/homeassistant-au-nsw-covid/issues/17

**Comment by troykelly** [comment]
Might also be from
```text
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 502, in __track
    await self.__refresh(event_receiver)
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 492, in __refresh
    await self.__protocol.api_get()
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/protocol.py", line 230, in api_get
    return await self.api("GET", path=path, data=data, host=host)
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/protocol.py", line 185, in api
    body = await self.__loop.run_in_executor(
  File "/usr/local/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/protocol.py", line 171, in process_request
    return self.__request(
  File "/usr/local/python/lib/python3.9/site-packages/nswcovid/protocol/protocol.py", line 89, in __request
    status_code = getattr(response, "status_code", None)
UnboundLocalError: local variable 'response' referenced before assignment
make: *** [Makefile:19: start] Interrupt
```

**Comment by troykelly** [comment]
Resolved
