### ISSUE TITLE
Failing to handle missing data

### ISSUE THREAD

**Issue by troykelly** [troykelly/python-nswcovid#41]
```text
DEBUG    nswcovid.protocol.statistics:statistics.py:114 Lives Lost Female 0 to 9 getting value (lives_lost_female_0_9)
DEBUG    urllib3.connectionpool:connectionpool.py:939 Starting new HTTPS connection (1): nswdac-covid-19-postcode-heatmap.azurewebsites.net:443
DEBUG    urllib3.connectionpool:connectionpool.py:433 https://nswdac-covid-19-postcode-heatmap.azurewebsites.net:443 "GET /datafiles/fatalitiesdata.json HTTP/1.1" 200 272
DEBUG    nswcovid.protocol.protocol:protocol.py:111 [GET] (553 bytes) https://nswdac-covid-19-postcode-heatmap.azurewebsites.net/datafiles/fatalitiesdata.json
ERROR    nswcovid.protocol.statistics:statistics.py:196 list_dict_data: {'data': [{'ageGroup': None, 'Males': None, 'Females': None}, {'ageGroup': '0-9', 'Males': None, 'Females': None}, {'ageGroup': '10-19', 'Males': 1, 'Females': None}, {'ageGroup': '20-29', 'Males': 1, 'Females': None}, {'ageGroup': '30-39', 'Males': 2, 'Females': 2}, {'ageGroup': '40-49', 'Males': 1, 'Females': 2}, {'ageGroup': '50-59', 'Males': None, 'Females': 3}, {'ageGroup': '60-69', 'Males': 12, 'Females': 3}, {'ageGroup': '70-79', 'Males': 23, 'Females': 12}, {'ageGroup': '80-89', 'Males': 32, 'Females': 24}, {'ageGroup': '90+', 'Males': 13, 'Females': 17}]}
ERROR    nswcovid.protocol.statistics:statistics.py:200 json_search: [data.Females for data in _.data if "0-9" in data.ageGroup]
ERROR    nswcovid.protocol.statistics:statistics.py:204 argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/workspaces/python-nswcovid/src/nswcovid/protocol/statistics.py", line 192, in details
    value = pyquery(list_dict_data, statistic.json_search)
  File "/home/vscode/.local/lib/python3.9/site-packages/jello/lib.py", line 396, in pyquery
    _θ_output = eval(compile(_θ_last, '<string>', mode='eval'))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by troykelly** [comment]
In the interest of being helpful, it looks like NSW Health have added a bunch of Null's to the data.
```json
{
    "data": [
        {
            "Females": null,
            "Males": null,
            "ageGroup": null
        },
        {
            "Females": 1393,
            "Males": 1461,
            "ageGroup": "0-9"
        },
        {
            "Females": 1870,
            "Males": 1883,
            "ageGroup": "10-19"
        },
        {
            "Females": 2694,
            "Males": 3095,
            "ageGroup": "20-29"
        },
        {
            "Females": 2094,
            "Males": 2442,
            "ageGroup": "30-39"
        },
        {
            "Females": 1434,
            "Males": 1636,
            "ageGroup": "40-49"
        },
        {
            "Females": 1261,
            "Males": 1417,
            "ageGroup": "50-59"
        },
        {
            "Females": 764,
            "Males": 841,
            "ageGroup": "60-69"
        },
        {
            "Females": 371,
            "Males": 458,
            "ageGroup": "70-79"
        },
        {
            "Females": 182,
            "Males": 171,
            "ageGroup": "80-89"
        },
        {
            "Females": 69,
            "Males": 44,
            "ageGroup": "90+"
        }
    ]
}
```
